server:
  port: ${SERVER_PORT:8081}
  max-http-request-header-size: 64KB

spring:
  application:
    name: gateway-api
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: ${CONSUL_PREFER_IP:false}
        hostname: ${CONSUL_DISCOVERY_HOSTNAME:localhost}
        instance-id: ${spring.application.name}:${random.value}
        heartbeat:
          enabled: true
        health-check-enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts,/accounts/**
          filters:
            - StripPrefix=0
        - id: cash-service
          uri: lb://cash-service
          predicates:
            - Path=/cash,/cash/**
          filters:
            - StripPrefix=0
        - id: transfer-service
          uri: lb://transfer-service
          predicates:
            - Path=/transfer,/transfer/**
          filters:
            - StripPrefix=0
        - id: notifications-service
          uri: lb://notifications-service
          predicates:
            - Path=/notifications,/notifications/**
          filters:
            - StripPrefix=0
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8082/realms/bank-realm}